# Usar una imagen base de .NET SDK para construir la aplicación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copiar el archivo csproj y restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar el resto del código y construir la aplicación
COPY . ./
RUN dotnet publish -c Release -o out

# Usar una imagen base de .NET Runtime para ejecutar la aplicación
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Crear la carpeta Data antes de copiar la base de datos
RUN mkdir -p ./Data

# Copiar los archivos publicados y la base de datos
COPY --from=build-env /app/out .
COPY Data/cancionito.db ./Data/cancionito.db

# Exponer el puerto en el que escucha la aplicación
EXPOSE 10000

# ENTRYPOINT para ejecutar la aplicación
ENTRYPOINT ["dotnet", "Cancionito.dll", "--urls", "http://*:10000"]
