# Usar una imagen base de .NET SDK para construir la aplicación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /cancionito

# Copiar el archivo csproj y restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar el resto del código y construir la aplicación
COPY . ./
RUN dotnet publish -c Release -o out

# Usar una imagen base de .NET Runtime para ejecutar la aplicación
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /cancionito
COPY --from=build-env /cancionito/out ./

# Exponer el puerto en el que escucha la aplicación
EXPOSE 80

# Ejecutar migraciones y luego iniciar la aplicación
ENTRYPOINT ["sh", "-c", "exec dotnet Cancionito.dll"]
